name: ci
on: [push]

jobs:
  aoc-2023-rust:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build package
        run: cd 2023/aoc && cargo build --release
      -
        name: Run tests
        run: cd 2023/aoc && cargo test
